version: '1.0'

services:
  nodecli:
    container_name: nodecli
    image: nodecli
    build:
      context: ./cli
      dockerfile: cli.dockerfile 
    depends_on:
      - nodesmsgateway
      - nodeussdgateway
    networks:
      - gsma-bridge
    environment:
      - SMS_GATEWAY_URL=http://nodesmsgateway:4000
      - USSD_GATEWAY_URL=http://nodeussdgateway:4100

  nodesmsgateway:
    container_name: nodesmsgateway
    image: nodesmsgateway
    build:
      context: ./sms-gateway
      dockerfile: sms-gateway.dockerfile
    networks:
      - gsma-bridge

  nodeussdgateway:
    container_name: nodeussdgateway
    image: nodeussdgateway
    build:
      context: ./ussd-gateway
      dockerfile: ussd-gateway.dockerfile
    ports:
      - "4100:4100"
    networks:
      - gsma-bridge

networks:
  gsma-bridge:
    driver: bridge