  version: '3.3'

  services:
    nodeproxy:
      container_name: nodeproxy
      image: gsmainclusivetechlab/token:proxy-v1.0.2

      ports:
        - "4000:4000"
      networks:
        - gsma-bridge
      environment:
        - SMS_GATEWAY_API_URL=http://nodesmsgateway:4100
        - USSD_GATEWAY_API_URL=http://nodeussdgateway:4200
      depends_on:
        nodesmsgateway:
          condition: service_healthy
        nodeussdgateway:
          condition: service_healthy 

    nodesmsgateway:
      container_name: nodesmsgateway
      image: gsmainclusivetechlab/token:sms-gateway-v1.0.2

      ports:
        - "4100:4100"
      networks:
        - gsma-bridge
      environment:
        - ENGINE_API_URL=http://engineservice:4400
        - PROXY_API_URL=http://nodeproxy:4000
      depends_on:
        engineservice:
          condition: service_healthy
      healthcheck:
        test: curl -f http://localhost:4100/health
        interval: 1s
        timeout: 3s
        retries: 10     

    nodeussdgateway:
      container_name: nodeussdgateway
      image: gsmainclusivetechlab/token:ussd-gateway-v1.0.2

      ports:
        - "4200:4200"
      networks:
        - gsma-bridge
      environment:
        - ENGINE_API_URL=http://engineservice:4400
        - PROXY_API_URL=http://nodeproxy:4000
      depends_on:
        engineservice:
          condition: service_healthy
      healthcheck:
        test: curl -f http://localhost:4200/health
        interval: 1s
        timeout: 3s
        retries: 10  

    tokenservice:
      container_name: tokenservice
      image: gsmainclusivetechlab/token:generator-v1.0.2

      ports:
        - "3700:3700"
      networks:
        - gsma-bridge
      environment:
        - HOST=tokendbservice
        - DB_USER=gsma-sa
        - DB_PASSWORD=password
        - DB_DATABASE=tokens
      depends_on:
        tokendbservice:
          condition: service_healthy
      healthcheck:
        test: curl -f http://localhost:3700/health
        interval: 1s
        timeout: 3s
        retries: 10

    tokendbservice:
      container_name: tokendbservice
      image: gsmainclusivetechlab/token:generator-db-v1.0.1
      command: --default-authentication-plugin=mysql_native_password

      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=R%9FovC$RRR3&Eb#RozM
        - MYSQL_USER=gsma-sa
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=tokens
      networks:
        - gsma-bridge
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

    engineservice:
      container_name: nodeengineservice
      image: gsmainclusivetechlab/token:engine-v1.0.2

      ports:
        - "4400:4400"
      networks:
        - gsma-bridge
      environment:
        - TOKEN_API_URL=http://tokenservice:3700
        - SMS_GATEWAY_API_URL=http://nodesmsgateway:4100
        - USSD_GATEWAY_API_URL=http://nodeussdgateway:4200
      depends_on:
        tokenservice:
          condition: service_healthy
      healthcheck:
        test: curl -f http://localhost:4400/health
        interval: 1s
        timeout: 3s
        retries: 10     

    client:
      container_name: client
      image: gsmainclusivetechlab/token:client-v1.0.2
      ports:
        - "8080:8080"
      networks:
        - gsma-bridge

  networks:
    gsma-bridge:
      driver: bridge
