  version: '3.3'

  services:
    nodeproxy:
      container_name: nodeproxy
      image: gsmainclusivetechlab/token:proxy-v1.5.0

      ports:
        - "4000:4000"
      networks:
        - gsma-bridge
      environment:
        - SMS_GATEWAY_API_URL=http://nodesmsgateway:4100
        - USSD_GATEWAY_API_URL=http://nodeussdgateway:4200
        - ENGINE_API_URL=http://engineservice:4400
      depends_on:
        nodesmsgateway:
          condition: service_healthy
        nodeussdgateway:
          condition: service_healthy

    nodesmsgateway:
      container_name: nodesmsgateway
      image: gsmainclusivetechlab/token:sms-gateway-v1.5.0

      ports:
        - "4100:4100"
      networks:
        - gsma-bridge
      environment:
        - ENGINE_API_URL=http://engineservice:4400
        - PROXY_API_URL=http://nodeproxy:4000
        - TWILIO_SID=${TWILIO_SID}
        - TWILIO_TOKEN=${TWILIO_TOKEN}
        - TWILIO_MESSAGE_SID=${TWILIO_MESSAGE_SID}
      depends_on:
        engineservice:
          condition: service_healthy
      healthcheck:
        test: curl -f http://localhost:4100/health
        interval: 1s
        timeout: 3s
        retries: 10

    nodeussdgateway:
      container_name: nodeussdgateway
      image: gsmainclusivetechlab/token:ussd-gateway-v1.5.0

      ports:
        - "4200:4200"
      networks:
        - gsma-bridge
      environment:
        - ENGINE_API_URL=http://engineservice:4400
        - PROXY_API_URL=http://nodeproxy:4000
      depends_on:
        engineservice:
          condition: service_healthy
      healthcheck:
        test: curl -f http://localhost:4200/health
        interval: 1s
        timeout: 3s
        retries: 10

    tokenservice:
      container_name: tokenservice
      image: gsmainclusivetechlab/token:generator-v1.4.0

      ports:
        - "3700:3700"
      networks:
        - gsma-bridge
      environment:
        - HOST=tokendbservice
        - DB_USER=root
        - DB_PASSWORD=1234
        - DB_DATABASE=registry
      depends_on:
        tokendbservice:
          condition: service_healthy
      healthcheck:
        test: curl -f http://localhost:3700/health
        interval: 1s
        timeout: 3s
        retries: 10

    tokendbservice:
      container_name: tokendbservice
      image: gsmainclusivetechlab/token:generator-db-v1.5.0
      command: --default-authentication-plugin=mysql_native_password

      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=1234
        - MYSQL_USER=root
        - MYSQL_DATABASE=registry
      networks:
        - gsma-bridge
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 3s
        retries: 10

    engineservice:
      container_name: nodeengineservice
      image: gsmainclusivetechlab/token:engine-v1.5.0

      ports:
        - "4400:4400"
      networks:
        - gsma-bridge
      environment:
        - TOKEN_API_URL=http://tokenservice:3700
        - SMS_GATEWAY_API_URL=http://nodesmsgateway:4100
        - USSD_GATEWAY_API_URL=http://nodeussdgateway:4200
        - MMO_API_URL=http://mmoservice:4300
        - PROXY_API_URL=http://nodeproxy:4000
        - ENGINE_API_URL=http://engineservice:4400
      depends_on:
        tokenservice:
          condition: service_healthy
      healthcheck:
        test: curl -f http://localhost:4400/health
        interval: 1s
        timeout: 3s
        retries: 10     

    mmoservice:
      container_name: mmoservice
      image: gsmainclusivetechlab/token:mmo-v1.4.0
      ports:
        - "4300:4300"
      networks:
        - gsma-bridge
      environment:
        - HOST=tokendbservice
        - DB_USER=root
        - DB_PASSWORD=1234
        - DB_DATABASE=registry
      depends_on:
        tokendbservice:
          condition: service_healthy
      healthcheck:
        test: curl -f http://localhost:4300/health
        interval: 1s
        timeout: 3s
        retries: 10

    client:
       container_name: client
       image: gsmainclusivetechlab/token:client-v1.4.2
       ports:
         - "8080:80"
       networks:
         - gsma-bridge

  networks:
    gsma-bridge:
      driver: bridge
