version: '3.3'

services:
  nodeproxy:
    container_name: nodeproxy
    image: nodeproxy
    build:
      context: ./proxy
      dockerfile: proxy.dockerfile 
    ports:
      - "4000:4000"
    depends_on:
      - nodesmsgateway
      - nodeussdgateway
    networks:
      - gsma-bridge
    environment:
      - SMS_GATEWAY_URL=http://nodesmsgateway:4100
      - USSD_GATEWAY_URL=http://nodeussdgateway:4200

  nodesmsgateway:
    container_name: nodesmsgateway
    image: nodesmsgateway
    build:
      context: ./sms-gateway
      dockerfile: sms-gateway.dockerfile
    ports:
      - "4100:4100"
    networks:
      - gsma-bridge

  nodeussdgateway:
    container_name: nodeussdgateway
    image: nodeussdgateway
    build:
      context: ./ussd-gateway
      dockerfile: ussd-gateway.dockerfile
    ports:
      - "4200:4200"
    networks:
      - gsma-bridge

networks:
  gsma-bridge:
    driver: bridge