export interface TwilioHookBody {
  ToCountry: string,
  ToState: string,
  SmsMessageSid: string,
  NumMedia: string,
  ToCity: string,
  FromZip: string,
  SmsSid: string,
  FromState: string,
  SmsStatus: string,
  FromCity: string,
  Body: string,
  FromCountry: string,
  To: string,
  MessagingServiceSid: string,
  ToZip: string,
  NumSegments: string,
  MessageSid: string,
  AccountSid: string,
  From: string,
  ApiVersion: string
}
