name: Mmo
env:
  CI: true
  BASE_TAG: gsmainclusivetechlab/token:mmo-v
on: [push]
jobs:
  release:
    name: Build Mmo
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./mmo
      - name: Build mmo image
        working-directory: ./mmo
        run: docker build . -f *.dockerfile --tag ${{env.BASE_TAG}}${{ steps.package-version.outputs.current-version}}
      - name: Docker Login
        if: github.ref == 'refs/heads/release'
        uses: docker/login-action@v1.12.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Push docker image
        if: github.ref == 'refs/heads/release'
        run: docker push ${{env.BASE_TAG}}${{ steps.package-version.outputs.current-version}}
