name: Publish proxy
env:
  CI: true
  BASE_TAG: gsmainclusivetechlab/token:proxy-v
on:
  push:
    branches:
      - feature/cicd
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./proxy
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build proxy image
        working-directory: ./proxy
        run: docker build . -f *.dockerfile --tag ${{env.BASE_TAG}}${{ steps.package-version.outputs.current-version}}
      - name: Push proxy image
        run: docker push ${{env.BASE_TAG}}${{ steps.package-version.outputs.current-version}}
