name: publish token
env:
  CI: true
on: [push]
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./token
      - name: print-version
        run: echo ${{ steps.package-version.outputs.current-version}}
      - name: print-dir
        run: ls
