name: publish token
env:
  CI: true
on: [push]
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./token
      - name: Build
        run: echo ${{ steps.package-version.outputs.current-version}}
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{secret.DOCKER_USERNAME}}
          password: ${{secret.DOCKER_TOKEN}}
      # - name: Build the Docker image
      #   working-directory: ./token
      #   run: docker build . -f *.dockerfile --tag generator:$(date +%s)
