name: publish token
env:
  CI: true
on: [push]
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./token
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build generator image
        working-directory: ./token
        run: docker build . -f *.dockerfile --tag token:generator-v${{ steps.package-version.outputs.current-version}}
      - name: Push generator image
        run: docker push token:generator-v${{ steps.package-version.outputs.current-version}}
